Superheroes/Heroes/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'Heroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete/<int:hero_id>/', views.delete, name='delete'),
    path('edit/<int:hero_id>/', views.edit, name='edit')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Superheroes/Superheroes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Heroes/', include('Heroes.urls')),
    path('', RedirectView.as_view(url='/Heroes/'))
]

Superheroes/Heroes/models.py
from django.db import models

# Create your models here.
class Hero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

Superheroes/Heroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Hero
# Create your views here.
def index(request):
    all_heroes = Hero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'Heroes/index.html', context)

def detail(request, hero_id):
    single_hero = Hero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'Heroes/details.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Hero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('Heroes:index'))
    else:
        return render(request, 'Heroes/create.html')
    
def delete(request, hero_id):
    if request.method == "POST":
        single_hero = Hero.objects.get(pk=hero_id)
        single_hero.delete()
        return HttpResponseRedirect(reverse('Heroes:index'))
    else:
        single_hero = Hero.objects.get(pk=hero_id)
        context = {
            'single_hero': single_hero
        }
        return render(request, 'Heroes/delete.html', context)

def edit (request, hero_id):
    if request.method == "POST":
        single_hero = Hero.objects.get(pk=hero_id)
        single_hero.name = request.POST.get('name')
        single_hero.alter_ego = request.POST.get('alter_ego')
        single_hero.primary = request.POST.get('primary')
        single_hero.secondary = request.POST.get('secondary')
        single_hero.catchphrase = request.POST.get('catchphrase')
        single_hero.save()
        return HttpResponseRedirect(reverse('Heroes:index'))
    else:
        single_hero = Hero.objects.get(pk=hero_id)
        context = {
            'single_hero': single_hero
        }
        return render(request, 'Heroes/edit.html', context)

Superheroes/Heroes/templates/Heroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'Heroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form> 
    
</body>
</html>

Superheroes/Heroes/templates/Heroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Hero</title>
</head>
<body>
    <h1>Are you sure you want to delete {{single_hero}} </h1>
    <form action="{% url 'Heroes:delete' single_hero.id %}" method="post">
        {% csrf_token %}
    <input type="submit" value="Delete"></form>
</body>
</html>

Superheroes/Heroes/templates/Heroes/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>
<body>
    <h1>{{single_hero}}</h1>
    <ul>
        <li><h2>{{single_hero.name}}</h2></li>
        <li><h2>{{single_hero.alter_ego}}</h2></li>
        <li><h2>{{single_hero.primary_ability}}</h2></li>
        <li><h2>{{single_hero.secondary_ability}}</h2></li>
        <li><h2>{{single_hero.catch_phrase}}</h2></li>
    </ul>
    
</body>
</html>

Superheroes/Heroes/templates/Heroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
</head>
<body>
    <form action="{% url 'Heroes:edit' single_hero.id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Replace!">
</form> 
    
</body>
</html>

Superheroes/Heroes/templates/Heroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <a href="{% url 'Heroes:create' %}">Add New Heroes</a>
    <ul>
        {% for hero in all_heroes%}
        <li> <h2>{{hero.name}} - <a href="{% url 'Heroes:detail' hero.id %}">Click for Details</a>
             - <a href="{% url 'Heroes:delete' hero.id %}">Delete</a> - <a href="{% url 'Heroes:edit' hero.id %}">Edit Hero</a></h2> </li> 
        {% endfor %}
    </ul>
    <img src="{% static 'superheroes/spidey.jpg' %}" alt="Oops the picture couldn't load!">
</body>
</html>